swagger: "2.0"
info:
  title: 'gpt-service'
  description: 'gpt后端接口swagger文档'
  version: '0.1'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - http
basePath: /v1
paths:
  /user/save:
    post:
      tags:
        - "User"
      summary: "save user"
      description: "return init password"
      operationId: saveUser
      produces:
        - "application/json"
      parameters:
        - in: body
          name: "user"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: "operate success"
          schema:
            type: object
            $ref: "#/definitions/Response"

definitions:
  Response:
    type: object
    properties:
      success:
        type: boolean
      code:
        type: string
      message:
        type: string
      data:
        type: object

  User:
    type: object
    required:
      - userNumber
      - userNameEn
      - userNameHe
      - userNameAr
    properties:
      id:
        type: integer
        format: int64
      userNumber:
        type: string
      userNameEn:
        type: string
      userNameHe:
        type: string
      userNameAr:
        type: string
      phone:
        type: string
        pattern: (\d{10})?
      userStatus:
        type: string
      operatorNumber:
        type: string
