spring:
  datasource:
    name: essy
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      load-on-startup: 1
    #    数据库自己写自己的，这个小demo应该不需要数据库配置，随便写一个或者把pom文件的数据库依赖干掉

